application: flashbook-app
version: ci

runtime: python27
threadsafe: true
instance_class: F1
api_version: 1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico